development:
  adapter: postgresql
  username: wei
  database: movie_hard_drive_development
  password:
  host: localhost

test:
  adapter: postgresql
  username: wei
  database: movie_hard_drive_test
  password:
  host: localhost

production:
  adapter: postgresql
  username: wei
  database: movie_hard_drive_production
  password:
  host: localhost